<?php

/*
 * This file is part of the PHP-UNDERSCORE package.
 *
 * (c) Jitendra Adhikari <jiten.adhikary@gmail.com>
 *     <https://github.com/adhocore>
 *
 * Licensed under MIT license.
 */

namespace Ahc\Underscore\Test;

use Ahc\Underscore\HigherOrderMessage;
use PHPUnit\Framework\TestCase as TestCase;

/**
 * Auto generated by `phint test`.
 */
class HigherOrderMessageTest extends TestCase
{
    /**
     * @var HigherOrderMessage
     */
    protected $hom1;

    /**
     * @var HigherOrderMessage
     */
    protected $hom2;

    public function setUp()
    {
        parent::setUp();

        $this->hom1 = new HigherOrderMessage(
            underscore([
                ['a' => 1, 'b' => 2],
            ]),
            'map'
        );

        $this->hom2 = new HigherOrderMessage(
            underscore([
                new class {
                    public $b = 'B';

                    public function a()
                    {
                        return 'A';
                    }
                },
            ]),
            'map'
        );
    }

    public function test_call()
    {
        $actual = $this->hom2->a()->get();

        $this->assertSame(['A'], $actual);
    }

    public function test_get()
    {
        $actual = $this->hom1->b->get();

        $this->assertSame([2], $actual);

        $actual = $this->hom2->b->get();

        $this->assertSame(['B'], $actual);
    }
}
